(function () {
  "use strict";

  // ICAO / ISO 3166-1 alpha-3 country code → [English name, phone dialling code].
  // Used to drive Birth Country, Birth City fallback, and the mobile country code
  // from the passport MRZ, for ANY nationality. The MRZ issuing-country / nationality
  // field is always one of these codes.
  const DATA = {
    AFG: ["Afghanistan", "+93"], ALB: ["Albania", "+355"], DZA: ["Algeria", "+213"],
    AND: ["Andorra", "+376"], AGO: ["Angola", "+244"], ATG: ["Antigua and Barbuda", "+1"],
    ARG: ["Argentina", "+54"], ARM: ["Armenia", "+374"], AUS: ["Australia", "+61"],
    AUT: ["Austria", "+43"], AZE: ["Azerbaijan", "+994"], BHS: ["Bahamas", "+1"],
    BHR: ["Bahrain", "+973"], BGD: ["Bangladesh", "+880"], BRB: ["Barbados", "+1"],
    BLR: ["Belarus", "+375"], BEL: ["Belgium", "+32"], BLZ: ["Belize", "+501"],
    BEN: ["Benin", "+229"], BTN: ["Bhutan", "+975"], BOL: ["Bolivia", "+591"],
    BIH: ["Bosnia and Herzegovina", "+387"], BWA: ["Botswana", "+267"], BRA: ["Brazil", "+55"],
    BRN: ["Brunei", "+673"], BGR: ["Bulgaria", "+359"], BFA: ["Burkina Faso", "+226"],
    BDI: ["Burundi", "+257"], CPV: ["Cabo Verde", "+238"], KHM: ["Cambodia", "+855"],
    CMR: ["Cameroon", "+237"], CAN: ["Canada", "+1"], CAF: ["Central African Republic", "+236"],
    TCD: ["Chad", "+235"], CHL: ["Chile", "+56"], CHN: ["China", "+86"],
    COL: ["Colombia", "+57"], COM: ["Comoros", "+269"], COG: ["Congo", "+242"],
    COD: ["Democratic Republic of the Congo", "+243"], CRI: ["Costa Rica", "+506"],
    CIV: ["Cote d'Ivoire", "+225"], HRV: ["Croatia", "+385"], CUB: ["Cuba", "+53"],
    CYP: ["Cyprus", "+357"], CZE: ["Czechia", "+420"], DNK: ["Denmark", "+45"],
    DJI: ["Djibouti", "+253"], DMA: ["Dominica", "+1"], DOM: ["Dominican Republic", "+1"],
    ECU: ["Ecuador", "+593"], EGY: ["Egypt", "+20"], SLV: ["El Salvador", "+503"],
    GNQ: ["Equatorial Guinea", "+240"], ERI: ["Eritrea", "+291"], EST: ["Estonia", "+372"],
    SWZ: ["Eswatini", "+268"], ETH: ["Ethiopia", "+251"], FJI: ["Fiji", "+679"],
    FIN: ["Finland", "+358"], FRA: ["France", "+33"], GAB: ["Gabon", "+241"],
    GMB: ["Gambia", "+220"], GEO: ["Georgia", "+995"], DEU: ["Germany", "+49"], D: ["Germany", "+49"],
    GHA: ["Ghana", "+233"], GRC: ["Greece", "+30"], GRD: ["Grenada", "+1"],
    GTM: ["Guatemala", "+502"], GIN: ["Guinea", "+224"], GNB: ["Guinea-Bissau", "+245"],
    GUY: ["Guyana", "+592"], HTI: ["Haiti", "+509"], HND: ["Honduras", "+504"],
    HKG: ["Hong Kong", "+852"], HUN: ["Hungary", "+36"], ISL: ["Iceland", "+354"],
    IND: ["India", "+91"], IDN: ["Indonesia", "+62"], IRN: ["Iran", "+98"],
    IRQ: ["Iraq", "+964"], IRL: ["Ireland", "+353"], ISR: ["Israel", "+972"],
    ITA: ["Italy", "+39"], JAM: ["Jamaica", "+1"], JPN: ["Japan", "+81"],
    JOR: ["Jordan", "+962"], KAZ: ["Kazakhstan", "+7"], KEN: ["Kenya", "+254"],
    KIR: ["Kiribati", "+686"], PRK: ["North Korea", "+850"], KOR: ["South Korea", "+82"],
    KWT: ["Kuwait", "+965"], KGZ: ["Kyrgyzstan", "+996"], LAO: ["Laos", "+856"],
    LVA: ["Latvia", "+371"], LBN: ["Lebanon", "+961"], LSO: ["Lesotho", "+266"],
    LBR: ["Liberia", "+231"], LBY: ["Libya", "+218"], LIE: ["Liechtenstein", "+423"],
    LTU: ["Lithuania", "+370"], LUX: ["Luxembourg", "+352"], MAC: ["Macao", "+853"],
    MDG: ["Madagascar", "+261"], MWI: ["Malawi", "+265"], MYS: ["Malaysia", "+60"],
    MDV: ["Maldives", "+960"], MLI: ["Mali", "+223"], MLT: ["Malta", "+356"],
    MHL: ["Marshall Islands", "+692"], MRT: ["Mauritania", "+222"], MUS: ["Mauritius", "+230"],
    MEX: ["Mexico", "+52"], FSM: ["Micronesia", "+691"], MDA: ["Moldova", "+373"],
    MCO: ["Monaco", "+377"], MNG: ["Mongolia", "+976"], MNE: ["Montenegro", "+382"],
    MAR: ["Morocco", "+212"], MOZ: ["Mozambique", "+258"], MMR: ["Myanmar", "+95"],
    NAM: ["Namibia", "+264"], NRU: ["Nauru", "+674"], NPL: ["Nepal", "+977"],
    NLD: ["Netherlands", "+31"], NZL: ["New Zealand", "+64"], NIC: ["Nicaragua", "+505"],
    NER: ["Niger", "+227"], NGA: ["Nigeria", "+234"], MKD: ["North Macedonia", "+389"],
    NOR: ["Norway", "+47"], OMN: ["Oman", "+968"], PAK: ["Pakistan", "+92"],
    PLW: ["Palau", "+680"], PSE: ["Palestine", "+970"], PAN: ["Panama", "+507"],
    PNG: ["Papua New Guinea", "+675"], PRY: ["Paraguay", "+595"], PER: ["Peru", "+51"],
    PHL: ["Philippines", "+63"], POL: ["Poland", "+48"], PRT: ["Portugal", "+351"],
    PRI: ["Puerto Rico", "+1"], QAT: ["Qatar", "+974"], ROU: ["Romania", "+40"],
    RUS: ["Russia", "+7"], RWA: ["Rwanda", "+250"], KNA: ["Saint Kitts and Nevis", "+1"],
    LCA: ["Saint Lucia", "+1"], VCT: ["Saint Vincent and the Grenadines", "+1"],
    WSM: ["Samoa", "+685"], SMR: ["San Marino", "+378"], STP: ["Sao Tome and Principe", "+239"],
    SAU: ["Saudi Arabia", "+966"], SEN: ["Senegal", "+221"], SRB: ["Serbia", "+381"],
    SYC: ["Seychelles", "+248"], SLE: ["Sierra Leone", "+232"], SGP: ["Singapore", "+65"],
    SVK: ["Slovakia", "+421"], SVN: ["Slovenia", "+386"], SLB: ["Solomon Islands", "+677"],
    SOM: ["Somalia", "+252"], ZAF: ["South Africa", "+27"], SSD: ["South Sudan", "+211"],
    ESP: ["Spain", "+34"], LKA: ["Sri Lanka", "+94"], SDN: ["Sudan", "+249"],
    SUR: ["Suriname", "+597"], SWE: ["Sweden", "+46"], CHE: ["Switzerland", "+41"],
    SYR: ["Syria", "+963"], TWN: ["Taiwan", "+886"], TJK: ["Tajikistan", "+992"],
    TZA: ["Tanzania", "+255"], THA: ["Thailand", "+66"], TLS: ["Timor-Leste", "+670"],
    TGO: ["Togo", "+228"], TON: ["Tonga", "+676"], TTO: ["Trinidad and Tobago", "+1"],
    TUN: ["Tunisia", "+216"], TUR: ["Turkey", "+90"], TKM: ["Turkmenistan", "+993"],
    TUV: ["Tuvalu", "+688"], UGA: ["Uganda", "+256"], UKR: ["Ukraine", "+380"],
    ARE: ["United Arab Emirates", "+971"], GBR: ["United Kingdom", "+44"],
    USA: ["United States", "+1"], URY: ["Uruguay", "+598"], UZB: ["Uzbekistan", "+998"],
    VUT: ["Vanuatu", "+678"], VAT: ["Vatican City", "+379"], VEN: ["Venezuela", "+58"],
    VNM: ["Vietnam", "+84"], YEM: ["Yemen", "+967"], ZMB: ["Zambia", "+260"],
    ZWE: ["Zimbabwe", "+263"], RKS: ["Kosovo", "+383"], XKX: ["Kosovo", "+383"],
    GRL: ["Greenland", "+299"],
  };

  window.NkCountries = {
    // English country name for an ICAO code, or "" if unknown.
    name: (code) => (code && DATA[code] ? DATA[code][0] : ""),
    // Phone dialling code for an ICAO code, or "" if unknown.
    dial: (code) => (code && DATA[code] ? DATA[code][1] : ""),
  };
})();
