(function () {
  "use strict";

  class ElementInspector {
    constructor(options = {}) {
      this.onSelect = options.onSelect || null;
      this.active = false;
      this.highlightedElement = null;
      this.previousStyles = null;

      this.handleHover = this.handleHover.bind(this);
      this.handleClick = this.handleClick.bind(this);
      this.handleKeydown = this.handleKeydown.bind(this);
    }

    start(onSelect) {
      if (this.active) this.stop();

      if (typeof onSelect === "function") {
        this.onSelect = onSelect;
      }

      this.active = true;
      document.addEventListener("mouseover", this.handleHover, true);
      document.addEventListener("click", this.handleClick, true);
      document.addEventListener("keydown", this.handleKeydown, true);
    }

    stop() {
      this.active = false;
      this.clearHighlight();
      document.removeEventListener("mouseover", this.handleHover, true);
      document.removeEventListener("click", this.handleClick, true);
      document.removeEventListener("keydown", this.handleKeydown, true);
    }

    handleHover(event) {
      if (!this.active) return;
      this.applyHighlight(event.target);
    }

    handleClick(event) {
      if (!this.active) return;

      event.preventDefault();
      event.stopPropagation();
      event.stopImmediatePropagation();

      const element = event.target;
      const detected = typeof window.detectElementType === "function"
        ? window.detectElementType(element)
        : { type: "button", meta: {} };

      const result = {
        element,
        selector: ElementInspector.getUniqueSelector(element),
        text: (element.innerText || element.textContent || "").trim(),
        elementType: detected.type,
        meta: detected.meta,
      };

      this.stop();

      if (typeof this.onSelect === "function") {
        this.onSelect(result);
      }
    }

    handleKeydown(event) {
      if (!this.active) return;
      if (event.key === "Escape" || event.key === "Esc") {
        event.preventDefault();
        event.stopPropagation();
        this.stop();
      }
    }

    applyHighlight(element) {
      if (this.highlightedElement === element) return;
      this.clearHighlight();

      this.highlightedElement = element;
      this.previousStyles = {
        border: element.style.border,
        backgroundColor: element.style.backgroundColor,
        cursor: element.style.cursor,
      };

      element.style.border = "2px solid #007bff";
      element.style.backgroundColor = "rgba(0, 123, 255, 0.12)";
      element.style.cursor = "crosshair";
    }

    clearHighlight() {
      if (!this.highlightedElement || !this.previousStyles) return;

      this.highlightedElement.style.border = this.previousStyles.border;
      this.highlightedElement.style.backgroundColor =
        this.previousStyles.backgroundColor;
      this.highlightedElement.style.cursor = this.previousStyles.cursor;

      this.highlightedElement = null;
      this.previousStyles = null;
    }

    // ── Angular/PrimeNG-aware selector engine ─────────────────────────────
    // Priority (each step only used if it produces a selector that is
    // actually unique on the page right now):
    //   1. a real, non-auto-generated id
    //   2. [formcontrolname] — Angular reactive forms; the single most
    //      reliable hook on this app (masar.nusuk.sa is all reactive forms)
    //   3. test hooks: data-testid / data-test / data-cy / data-qa
    //   4. [name] / [aria-label]
    //   5. tag + STABLE classes (framework noise already stripped)
    //   6. ancestor-scoped: climb a few parents looking for one of the
    //      above on an ancestor, then combine "ancestorSelector ownSelector"
    //      — this is what turns a non-unique class (many rows share it) or a
    //      TRANSIENT class (only present while the field has a value, is
    //      focused, etc.) into a selector that survives.
    //   7. full hierarchy walk (last resort, still noise-free)

    // Escape a value for safe use inside a CSS attribute selector's quotes
    // (CSS.escape is for bare identifiers like #id/.class, NOT quoted
    // attribute-value strings, so backslashes/quotes need their own escaping).
    static escAttrValue(v) {
      return String(v).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    }

    // PrimeNG/Angular Material/etc. mint ids like "pn_id_3", "ui-id-7" from a
    // page-load-order counter — they LOOK unique but shift the moment an
    // earlier component on the page mounts/unmounts differently. Treat them
    // as noise, same as the dynamic classes.
    static isAutoGeneratedId(id) {
      return /^(pn|pr|ui|mat|mdc)[-_]?id[-_]?\d+$/i.test(id) || /^ng-\d+$/i.test(id);
    }

    // A single attribute-selector fragment, or "" if the attribute is absent.
    static attrFrag(el, attr) {
      const v = el.getAttribute(attr);
      if (!v) return "";
      return `[${attr}="${ElementInspector.escAttrValue(v)}"]`;
    }

    // The element's own best selector fragment (tag + id/formcontrolname/
    // test-hook/name/aria-label/stable-classes) WITHOUT checking uniqueness —
    // used both standalone and as the tail of an ancestor-scoped selector.
    static getOwnSelector(element) {
      const tag = element.tagName.toLowerCase();
      if (element.id && !ElementInspector.isAutoGeneratedId(element.id)) {
        return `#${CSS.escape(element.id)}`;
      }
      const fcn = ElementInspector.attrFrag(element, "formcontrolname");
      if (fcn) return tag + fcn;
      for (const attr of ["data-testid", "data-test", "data-cy", "data-qa", "data-automation-id"]) {
        const f = ElementInspector.attrFrag(element, attr);
        if (f) return tag + f;
      }
      const nameFrag = ElementInspector.attrFrag(element, "name");
      if (nameFrag) return tag + nameFrag;
      const ariaFrag = ElementInspector.attrFrag(element, "aria-label");
      if (ariaFrag) return tag + ariaFrag;
      const classSelector = ElementInspector.getClassSelector(element);
      return classSelector || tag;
    }

    static getUniqueSelector(element) {
      if (!element || element.nodeType !== Node.ELEMENT_NODE) return "";

      if (element.id && !ElementInspector.isAutoGeneratedId(element.id)) {
        const sel = `#${CSS.escape(element.id)}`;
        if (ElementInspector.isUnique(sel)) return sel;
      }

      const tag = element.tagName.toLowerCase();

      // formcontrolname is the strongest hook on an Angular reactive-forms
      // page — almost always unique by itself (one control per name).
      const fcnFrag = ElementInspector.attrFrag(element, "formcontrolname");
      if (fcnFrag) {
        const sel = tag + fcnFrag;
        if (ElementInspector.isUnique(sel)) return sel;
      }

      for (const attr of ["data-testid", "data-test", "data-cy", "data-qa", "data-automation-id"]) {
        const f = ElementInspector.attrFrag(element, attr);
        if (f) {
          const sel = tag + f;
          if (ElementInspector.isUnique(sel)) return sel;
        }
      }

      const nameFrag = ElementInspector.attrFrag(element, "name");
      if (nameFrag) {
        const sel = tag + nameFrag;
        if (ElementInspector.isUnique(sel)) return sel;
      }

      const ariaFrag = ElementInspector.attrFrag(element, "aria-label");
      if (ariaFrag) {
        const sel = tag + ariaFrag;
        if (ElementInspector.isUnique(sel)) return sel;
      }

      const classSelector = ElementInspector.getClassSelector(element);
      if (classSelector && ElementInspector.isUnique(classSelector)) {
        return classSelector;
      }

      // Not unique alone (e.g. one of several identical filter buttons, or
      // the class is only present transiently) — scope it under the nearest
      // ancestor that DOES have a stable identity, e.g.
      // ".p-column-filter-constraint input.p-inputtext".
      const scoped = ElementInspector.getAncestorScopedSelector(element, classSelector || tag);
      if (scoped) return scoped;

      return ElementInspector.getHierarchySelector(element);
    }

    // Climb up to 6 ancestors; for the first one with a stable identity,
    // combine "ancestorSelector ownSelector" and use it if that's unique.
    static getAncestorScopedSelector(element, ownSelector) {
      let anc = element.parentElement;
      for (let depth = 0; anc && depth < 6; depth++, anc = anc.parentElement) {
        const ancId = anc.id && !ElementInspector.isAutoGeneratedId(anc.id) ? `#${CSS.escape(anc.id)}` : "";
        const ancClass = ElementInspector.getClassSelector(anc);
        const ancIdentity = ancId || ancClass;
        if (!ancIdentity) continue;
        const combo = `${ancIdentity} ${ownSelector}`;
        if (ElementInspector.isUnique(combo)) return combo;
      }
      return "";
    }

    static getClassSelector(element) {
      // Strip classes that change between renders/interactions — selectors
      // built from them fail on the next page load:
      //   • Angular form-state (ng-dirty, ng-touched, …)
      //   • Angular view-encapsulation ids (ng-tns-c808012047-25 — the number
      //     changes EVERY render) and structural markers (ng-star-inserted/removed)
      //   • Angular animation hooks (ng-trigger-*, ng-animate*)
      //   • PrimeNG transient state (p-focus, p-filled, p-highlight,
      //     p-placeholder, p-inputwrapper-filled/focus, p-overlay-open) —
      //     these only exist while the user is interacting / the field has a
      //     value, so a selector built from them works when captured but
      //     fails the moment the page is reloaded fresh
      //   • Bootstrap-family "currently open" toggle classes (show / open /
      //     in — the exact class name has changed across Bootstrap versions,
      //     all mean the same thing) on dropdowns/collapses/modals — picking
      //     an item FROM an open dropdown menu bakes in "and the menu must
      //     currently be open" as part of the selector, which is exactly
      //     backwards for something meant to open (or click inside) that
      //     same menu on demand. Deliberately NOT filtering "active" — far
      //     too often a legitimate, stable selector target (active tab,
      //     active list item), not a transient toggle like these are.
      const classes = [...element.classList].filter(
        (cls) => Boolean(cls)
          && !/^ng-(dirty|pristine|valid|invalid|touched|untouched|pending|submitted|star-inserted|star-removed|animating)$/.test(cls)
          && !/^ng-tns-/.test(cls)
          && !/^ng-trigger/.test(cls)
          && !/^ng-animate/.test(cls)
          && !/^p-(focus|filled|highlight|placeholder|overlay-open|inputwrapper-focus|inputwrapper-filled|dropdown-open)$/.test(cls)
          && !/^(show|open|in)$/.test(cls),
      );
      if (!classes.length) return "";

      return `${element.tagName.toLowerCase()}.${classes
        .map((className) => CSS.escape(className))
        .join(".")}`;
    }

    static getHierarchySelector(element) {
      const path = [];
      let current = element;

      while (current && current.nodeType === Node.ELEMENT_NODE) {
        let selector = ElementInspector.getOwnSelector(current);

        // Own selector may still not be unique at this level (e.g. a bare
        // tag, or a class shared by siblings) — disambiguate by position.
        const parent = current.parentElement;
        if (parent && !/[#[]/.test(selector)) {
          const siblings = [...parent.children].filter(
            (sibling) => sibling.tagName === current.tagName,
          );
          if (siblings.length > 1) {
            selector += `:nth-of-type(${siblings.indexOf(current) + 1})`;
          }
        }

        path.unshift(selector);
        const fullSelector = path.join(" > ");
        if (ElementInspector.isUnique(fullSelector)) return fullSelector;

        current = current.parentElement;
      }

      return path.join(" > ");
    }

    static isUnique(selector) {
      try {
        return document.querySelectorAll(selector).length === 1;
      } catch (err) {
        return false;
      }
    }
  }

  window.ElementInspector = ElementInspector;
})();
